### ISSUE TITLE
Assessment Tasksheets do not Generate or Download as Accessible PDFs

### ISSUE THREAD

**Issue by njsch** [doubtfire-lms/doubtfire-api#305]
Not sure whether this is a subjective, individual academic issue, or an actual OnTrack / Doubtfire issue.  Also not sure if it's a frontend web app or backend / API issue but assuming the latter for now.  FYI @jakerenzella.

Currently, the main issue appears to be that most tasksheets produce one of the following two problems: either the words in the document are rendered as a single string of characters with no whitespace, or otherwise each individual letter is rendered on its own line in a screen-reader's virtual viewer / buffer.  makes for very difficult reading.  The only way around this is to perform [OCR](https://en.wikipedia.org/wiki/Optical_character_recognition) on the text, which works in general but not specifically very well for things like extrapolating programming language syntax.  The OCR compromise also doesn't work if documents are password protected, unless one has the password.

**Comment by jakerenzella** [comment]
Hey @njsch,

The task sheets are not generated on OnTrack, they are created elsewhere by each unit chair and simply uploaded. Are you familiar with other examples of similar PDFs which contain code, that are a good example of screen-reader friendly behaviour? That may allow us to generate some "best practices" for how to create the PDFs. Otherwise I don't think there's much opportunity in the OnTrack pipeline for addressing this, other than changing the format of the task sheets to something like markdown (which I'm not ruling out as a longer-term solution).

Let me know your thoughts,

Jake

**Comment by njsch** [comment]
Closed #305 as is not a Doubtfire issue but may comment for further discussion.

**Comment by njsch** [comment]
@jakerenzella, I can try and find a document if you like but I'm a little busy atm.

**Comment by jakerenzella** [comment]
@njsch no problem, no rush! All the best
